// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDr-I_f7yzZPT4ut3imBlMSTrMKzHsBaXA',
    appId: '1:421939510727:web:a839b53149e5433a2dede2',
    messagingSenderId: '421939510727',
    projectId: 'flutter-application1-9f721',
    authDomain: 'flutter-application1-9f721.firebaseapp.com',
    storageBucket: 'flutter-application1-9f721.firebasestorage.app',
    measurementId: 'G-66HBRCJG99',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBaN_40LbkKAdFkhoLtx03f864PdLXcB_A',
    appId: '1:421939510727:android:072262730b7ce0172dede2',
    messagingSenderId: '421939510727',
    projectId: 'flutter-application1-9f721',
    storageBucket: 'flutter-application1-9f721.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBKtJj1QytAM0ZHyLVqL5pnLQ964RDSGCc',
    appId: '1:421939510727:ios:31742c55392174872dede2',
    messagingSenderId: '421939510727',
    projectId: 'flutter-application1-9f721',
    storageBucket: 'flutter-application1-9f721.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBKtJj1QytAM0ZHyLVqL5pnLQ964RDSGCc',
    appId: '1:421939510727:ios:31742c55392174872dede2',
    messagingSenderId: '421939510727',
    projectId: 'flutter-application1-9f721',
    storageBucket: 'flutter-application1-9f721.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDr-I_f7yzZPT4ut3imBlMSTrMKzHsBaXA',
    appId: '1:421939510727:web:f7255f0d2610cb4a2dede2',
    messagingSenderId: '421939510727',
    projectId: 'flutter-application1-9f721',
    authDomain: 'flutter-application1-9f721.firebaseapp.com',
    storageBucket: 'flutter-application1-9f721.firebasestorage.app',
    measurementId: 'G-R9FSZRFDMR',
  );
}
